### ISSUE TITLE
BVS() implementation incorrect?

### ISSUE THREAD

**Issue by MalcolmPhoenix** [f0lg0/6502#1]
Line 647 in src/cpu/instructions.c looks wrong to me. Shouldn't it compare to 1, not 0? As is, BVC() and BVS() seem to be identical:

```
static uint8_t BVS(void) {
    if (cpu_extract_sr(V) == 0) {        <--- compare to 1, not 0?
        branch();
    }
    return 0;
}
```
This is just based on inspection of the latest code in GitHub.  I haven't tried running the code.

**Comment by f0lg0** [comment]
yes it is indeed correct, as verified [here](https://www.masswerk.at/6502/6502_instruction_set.html#BVS). Will fix it ASAP

**Comment by f0lg0** [comment]
fixed in the latest commit, thanks for pointing it out!!
